---
- name: Setup dock for better developer experience
  ansible.builtin.include_role:
    name: geerlingguy.mac.dock
    apply:
      environment:
        PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"