---
- name: Disable first time setuo
  ansible.builtin.file:
    path: /var/db/.AppleSetupDone
    state: touch
    owner: root
    group: wheel
    mode: '0644'
    modification_time: preserve
    access_time: preserve
